config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/approval.rb
class Approval < ApplicationRecord
	belongs_to :approvable, polymorphic: true

	enum state: { pending: "pending", approved: "approved" }
end

app/models/comment.rb
class Comment < ApplicationRecord
	include Approvable
end

app/models/concerns/approvable.rb
module Approvable
  extend ActiveSupport::Concern

  included do
		has_one :approval, as: :approvable

    def self.requiring_approval
			joins(:approval)
		end

		def self.not_requiring_approval
			where.not(id: Approval.select(:approvable_id))
		end

		def self.approved
			requiring_approval.merge Approval.approved
		end

		def self.pending
			requiring_approval.merge Approval.pending
		end

		def approval_state
			try(:approval).try(:state) || :not_required
		end
  end
end

app/models/post.rb
class Post < ApplicationRecord
	include Approvable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:description)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>All Comments</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Approval State</th>
    </tr>
  </thead>

  <tbody>
    <% Comment.all.each do |comment| %>
      <tr>
        <td><%= comment.description %></td>
        <td><%= comment.approval_state %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr>

<h1>Approved Comments</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Approval State</th>
    </tr>
  </thead>

  <tbody>
    <% Comment.approved.each do |comment| %>
      <tr>
        <td><%= comment.description %></td>
        <td><%= comment.approval_state %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr>

<h1>Pending Comments</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Approval State</th>
    </tr>
  </thead>

  <tbody>
    <% Comment.pending.each do |comment| %>
      <tr>
        <td><%= comment.description %></td>
        <td><%= comment.approval_state %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr>

<h1>Comments Not Requiring Approval</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Approval State</th>
    </tr>
  </thead>

  <tbody>
    <% Comment.not_requiring_approval.each do |comment| %>
      <tr>
        <td><%= comment.description %></td>
        <td><%= comment.approval_state %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @comment.description %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApprovalsTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>All Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Approval State</th>
    </tr>
  </thead>

  <tbody>
    <% Post.all.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.approval_state %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr>

<h1>Approved Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Approval State</th>
    </tr>
  </thead>

  <tbody>
    <% Post.approved.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.approval_state %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr>

<h1>Pending Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Approval State</th>
    </tr>
  </thead>

  <tbody>
    <% Post.pending.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.approval_state %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr>

<h1>Posts Not Requiring Approval</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Approval State</th>
    </tr>
  </thead>

  <tbody>
    <% Post.not_requiring_approval.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.approval_state %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>